# Generated by Django 5.1.6 on 2025-03-04 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=20)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저 목록",
            },
        ),
    ]
