# Generated by Django 5.1.6 on 2025-03-05 04:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
