# Generated by Django 5.1.6 on 2025-03-04 08:13

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "post_transaction_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("transaction_detail", models.TextField(max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEPOSIT", "입금"), ("WITHDRAW", "출금")],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_method",
                    models.CharField(
                        choices=[
                            ("ATM", "ATM 거래"),
                            ("TRANSFER", "계좌이체"),
                            ("AUTOMATIC_TRANSFER", "자동이체"),
                            ("CARD", "카드결제"),
                            ("INTEREST", "이자"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_timestamp",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
            ],
        ),
    ]
