# Generated by Django 5.1.6 on 2025-03-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("transactions", "0002_transaction_history_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction_history",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.account",
            ),
        ),
    ]
